Module7 task3
htmlacademy-react/2063853-six-cities-simple-11 pull request #12
Opened 2022-12-01 17:26 UTC by LenaKorsakov

2022-12-03 01:08 UTC, AlexMasterov requested changes

2022-12-03 01:08 UTC, AlexMasterov commented on project/src/components/reviews-form/star-picker.tsx
>          <svg className="form__star-image" width={37} height={33}>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/205414011-a85246bc-bf7d-4823-b15c-8beab43204bc.png)

<details>
<summary>Разметка отличается (некритично)</summary>

![image](https://user-images.githubusercontent.com/700213/205414255-1c44cdba-f38c-4318-998e-3969597c351e.png)
![image](https://user-images.githubusercontent.com/700213/205414263-46b16d2b-deb5-4f1b-978e-e8d19ae1c608.png)
</details>
</details>

См. внимательно макет и стили `svg`.


<details>
<summary>hint: style</summary>

![image](https://user-images.githubusercontent.com/700213/205414895-b3f31584-0d57-4258-8ce2-fe488d69eec0.png)

</details>

2022-12-03 01:08 UTC, AlexMasterov commented on project/src/components/reviews-form/star-picker.tsx
См. ТЗ:
 > В случае успешной отправки, комментарий появляется в списке комментариев

Сейчас комментарий появляется не сразу, а после перезагрузки страницы.

2022-12-03 04:02 UTC, AlexMasterov commented on project/src/pages/offer-screen/offer-screen.tsx
> +      <LoadingScreen />
Желательно поднять выше, чтобы зря не выполнять след. код:
https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/5ba3a2ed7232be68f18e914873a41de8918f5bff/project/src/pages/offer-screen/offer-screen.tsx#L33-L38

2022-12-03 04:07 UTC, AlexMasterov commented on project/src/pages/offer-screen/offer-screen.tsx
>    } if (isDataLoading) {
<details>
<summary>pages/offer-screen/offer-screen.tsx</summary>

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/5ba3a2ed7232be68f18e914873a41de8918f5bff/project/src/pages/offer-screen/offer-screen.tsx#L26-L43
</details>

Неоптимальный порядок выполнения.

В случае `offer === null` не стоит делать кучу запросов на сервере.

2022-12-03 04:11 UTC, AlexMasterov commented on project/src/components/review-block/review-block.tsx
> +  //+ оказалось, что в state Date хранить нельзя
> оказалось, что в state Date хранить нельзя

А кто запретил? разве это не твой код? 🤔

2022-12-03 04:20 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +        id: offerId,
Может стоит добавить `id` (в новый объект) при вызове `sendReviewAction`, а не хранить его просто так в состояние компонента.

> Не критично

2022-12-03 04:24 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +    if(!isReviewSendingError) {
<details>
<summary>components/reviews-form/reviews-form.tsx</summary>

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/5ba3a2ed7232be68f18e914873a41de8918f5bff/project/src/components/reviews-form/reviews-form.tsx#L44-L50
</details>

Вся полезная работа функции зависит от одного значения `isReviewSendingError`, даже не параметра, а замыкание внешнего окружения. При этом функция создается всегда, а используется только в обработчике, который вызывается не всегда.

Может стоит перенести в обработчик или даже удалить, просто используя код в обработчике?

2022-12-03 04:33 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/205422964-26fdf6c1-04df-4d0e-88a5-35b211533fa6.png)

</details>


См. ТЗ:
> Пока пользователь не выбрал оценку и не ввёл текст допустимой длины, кнопка отправки отзыва не активна

2022-12-03 04:45 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +  //стоит ли разбивать на два отдельных стейта, чтобы избежать перерисовки? или это незначительно?
<details>
<summary>components/reviews-form/reviews-form.tsx</summary>

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/5ba3a2ed7232be68f18e914873a41de8918f5bff/project/src/components/reviews-form/reviews-form.tsx#L30-L35
https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/5ba3a2ed7232be68f18e914873a41de8918f5bff/project/src/components/reviews-form/reviews-form.tsx#L92-L93
</details>

Сейчас комментарий валидируется проверкой на длину только в при нажатии на кнопку отправки.

В таком случае вообще мало смысла хранить текст комментария.

Если хочешь оптимизировать, то можешь начать с использования `useRef`:
```js
const commentRef = useRef()

sendReviewAction({
  id: offerId,
  comment: commentRef.current.value,
  // rating
})
```

2022-12-03 04:53 UTC, AlexMasterov commented on project/src/components/review-block/review-block.tsx
> +  const reviews = useMemo( () => reviewsAdapted.slice(MIN_REVIEWS_COUNT, MAX_REVIEWS_COUNT).sort(sortData),[reviewsAdapted]);
reviewsAdapted.slice(`MIN_REVIEWS_COUNT`, MAX_REVIEWS_COUNT)

🤔

2022-12-04 10:57 UTC, LenaKorsakov commented on project/src/const/review.ts
> +export const MIN_REVIEWS_COUNT = 0;
это я каждый раз забываю, что slice не включает в себя элемент с индексом max( поэтому 9, а не 10

2022-12-06 19:33 UTC, AlexMasterov requested changes

2022-12-06 19:33 UTC, AlexMasterov commented on project/src/components/app/app.tsx
См. ТЗ:
> В случае возникновения ошибки следует уведомить пользователя. Способ отображения ошибки остаётся на усмотрение разработчика

Нужно доработать.

2022-12-06 19:33 UTC, AlexMasterov commented on project/src/components/app/app.tsx
См. ТЗ:
> В случае успешной отправки отзыва форма очищается

Сейчас форма очищается в случае возникновения ошибки.

2022-12-06 19:33 UTC, AlexMasterov commented on project/src/components/app/app.tsx
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/206004620-329874d9-e1bf-403e-ad5b-b9be4e80a5ec.png)

</details>

После неудачной попытки отправить форму в отсутствие сети у формы начинается странное поведение.

Нужно разобраться и исправить.

2022-12-06 19:40 UTC, AlexMasterov commented on project/src/utiles/get-random-item.ts
> +export const getRandomItem = <T>(items: T[]):T => (items[Math.floor(Math.random() * items.length)]);
`(`items[Math.floor(Math.random() * items.length)]`)`

🤔

2022-12-06 19:44 UTC, AlexMasterov commented on project/src/components/login-form/login-form.tsx
> +      const errorMessage = validatePassword(passwordRef.current.value) || validateLogin(emailRef.current.value);
![image](https://user-images.githubusercontent.com/700213/206007283-c8a7af5f-af51-43a5-9295-9425a7ef1c79.png)

Одновременное работает две валидации и у HTML5-валидации приоритет.

2022-12-08 10:56 UTC, LenaKorsakov commented on project/src/components/login-form/login-form.tsx
> +      const errorMessage = validatePassword(passwordRef.current.value) || validateLogin(emailRef.current.value);
Я убрала тип поля email теперь по умолчанию text.
Желтое предупреждение как на скрине появляется только если отправить email, вроде бы подходящий под паттерн, но не существующий в природе (если я не ошибаюсь, это обработка ответа от сервера в api)

2022-12-08 16:15 UTC, AlexMasterov commented on project/src/components/login-form/login-form.tsx
> +      if (errorMessage.length > 0) {
```diff
- if (errorMessage.length > 0) {
+ if (errorMessage === WarningMessage.NoError) {
```

2022-12-08 16:18 UTC, AlexMasterov commented on project/src/const/city-name.ts
`setupTests.ts`
`react-app-env.d.ts`

Сейчас не используются и к этому могут придраться.

2022-12-08 16:21 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +  const isReviewFormBloked = useAppSelector(checkIsReviewFormBlocked);
```diff
- const isReviewFormBloked = useAppSelector(checkIsReviewFormBlocked);
+ const isReviewFormBlocked = useAppSelector(checkIsReviewFormBlocked);
```

2022-12-08 16:23 UTC, merged