Module5 task1
htmlacademy-react/2063853-six-cities-simple-11 pull request #6
Opened 2022-11-04 16:36 UTC by LenaKorsakov

2022-11-04 18:26 UTC, AlexMasterov requested changes
Нужно доработать карту.

2022-11-04 18:26 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +          .addTo(map);
(пример)

Прежде, перед циклом, нужно создать группу слоев, используя [`l.layerGroup()`](https://leafletjs.com/reference.html#layergroup):

```js
const markerGroup = new LayerGroup();
```
После этого созданный маркер добавлять в него, а не карту:

 
```diff
- .addTo(map);
+ .addTo(markerGroup);
```
По заверению цикла, после него, добавь слой группы маркеров в карту:

```js
markerGroup.addTo(map);
```

2022-11-04 18:26 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +    }
В хуке `useEffect` на случай демонтирования компонента нужно предусмотреть удаление с карты слоя группы маркеров.

[`Д 20`](https://up.htmlacademy.ru/react/11/criteries#d20)
> При изменении состояния компонента в `useEffect` выполняется проверка на демонтирование компонента

2022-11-04 18:26 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +  return <div style={{height: '500px'}} ref={mapRef}></div>;
См. задание:
> Обратите внимание, карта отрисовывается в контейнере `.cities__map`

См. разметку в макете:
https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/589001c1c5e6e7c95932639a232f16f189e8840a/markup/main.html#L241

Желательно предусмотреть возможность переиспользовать компонент для:

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/589001c1c5e6e7c95932639a232f16f189e8840a/markup/property.html#L232

2022-11-04 18:38 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +          .addTo(map);
Еще желательно:

```js
const { latitude: lat, longitude: lng, zoom } = city.location;

map.setView({ lat, lng }, zoom, { animate: true });
```

2022-11-04 18:39 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +          .addTo(map);
Пожалуйста, добавь в `project`:

````
.gitignore
.gitattributes
``` 
И `.env` с содержанием:

```
ESLINT_NO_DEV_ERRORS=true
TSC_COMPILE_ON_ERROR=true
```
Как ты вообще без этого 🤔

2022-11-04 18:41 UTC, AlexMasterov commented on project/src/components/offers-list/offers-list.tsx
Пожалуйста, добавь в `project`:

```
.gitignore
.gitattributes
``` 
И `.env` с содержанием:

```
ESLINT_NO_DEV_ERRORS=true
TSC_COMPILE_ON_ERROR=true
```
Как ты вообще без этого 🤔

2022-11-04 18:57 UTC, AlexMasterov commented on project/src/enum/url-marker.ts
> +  CURRENT: 'https://assets.htmlacademy.ru/content/intensive/javascript-1/demo/interactive-map/main-pin.svg',
См.:
`markup/img/pin.svg`
`markup/img/pin-active.svg`

2022-11-04 19:03 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +          lng: offer.city.location.longitude
Нужно брать значения из `offer.location`

2022-11-05 12:14 UTC, LenaKorsakov commented on project/src/components/map/map.tsx
> +          .addTo(map);
"Нужно брать значения из offer.location 😃" . 

Какую же я глупую ошибку допустила, самой смешно) Думала, почему это у меня всего 1 маркер на карте вместо 4! А у меня просто центр города рисовался 4 раза.
Спасибо!

2022-11-05 18:22 UTC, AlexMasterov commented on project/src/enum/marker-url.ts
> +  Current: 'https://assets.htmlacademy.ru/content/intensive/javascript-1/demo/interactive-map/main-pin.svg',
Повторю, что на защите проекта могут придраться, что вместо иконок из макета проекта используются иконки из демонстрации.

2022-11-05 18:22 UTC, AlexMasterov commented on project/src/enum/marker-shape.ts
> +export const MarkerShape = {
<details>
<summary>components/map/map.tsx</summary>

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/95578bd4b1ad7dd85ceb164f795da19a183a6c91/project/src/components/map/map.tsx#L16-L26
</details>

Повторю, что на защите проекта могут придраться к названию переменных, которые указывают на постоянные объекты. Типы меток описаны в ТЗ, а вычисление их объектов не требует побочного эффекта и во время выполнении приложения они не меняются. Поэтому могут потребовать их переменные тоже записать в формате "константы".

Предлагаю оставить на усмотрение случайного проверяющего. Исправить название ничего не стоит.

2022-11-05 18:22 UTC, AlexMasterov commented on project/src/components/map/map.tsx
> +  const { latitude: lat, longitude: lng, zoom } = city.location;
> React Hook useEffect has missing dependencies: 'lat', 'lng', and 'zoom'. Either include them or remove the dependency array

Деструктуризируй объект внутри хука, как было показано в примере, или добавь их в зависимости.

2022-11-05 18:22 UTC, AlexMasterov commented on project/src/hooks/use-map.tsx
> +  const{latitude, longitude, zoom} = city.location;
> React Hook useEffect has missing dependencies: 'latitude', 'longitude', and 'zoom'. Either include them or remove the dependency array

https://github.com/htmlacademy-react/2063853-six-cities-simple-11/blob/95578bd4b1ad7dd85ceb164f795da19a183a6c91/project/src/hooks/use-map.tsx#L9

Деструктуризируй объект внутри хука или или добавь их в зависимости.

2022-11-05 18:22 UTC, merged

2022-11-06 10:59 UTC, LenaKorsakov commented on project/src/components/map/map.tsx
> +      isMapMounted = false;
Давай на созвоне этот момент еще раз обговорим: для меня было неочевидно, что слой маркеров, созданный при помощи useEffect не становится частью компонента, который после демонтируется весь. 

Поняла, что флаг isMapMounted был бы нужен, если бы действие внутри хука могло бы происходить с задержкой (ждали бы ответ от сервера).

2022-11-06 11:11 UTC, LenaKorsakov commented on project/src/components/map/map.tsx
> +  return <div style={{height: '500px'}} ref={mapRef}></div>;
Хотела бы про переиспользование поговорить на созвоне - как передавать нужный класс.